apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: goke
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: tests/secrets/secret.json
  - name: nestedSeparator
    value: ":"
